Minjin/gapchat
sb-jang/timely-chat pull request #5
Opened 2024-08-31 20:22 UTC by minjin-jeon

resources/gapchat 폴더 신설
- prompt.py : openai api를 활용해서 대화의 event, schedule를 생성, 추출하는 코드(gapchat 저자 코드 기반으로 수정)
- prepare_data.py : prompt.py로 추출한 event, schedule를 바탕으로 progress label을 생성, 세션에 맞도록 포맷팅하는 코드(gapchat 저자 코드 기반으로 수정)
- dataset : huggingface에 업로드한 gapchat dataset 파일
- gap_chat, events: gapchat 저자들이 제공하는 gapchat dataset
- new_data : prompt.py, prepare_data.py를 돌렸을 때 생성되는 데이터 파일
- timely_chat/dataset.py 수정

GapChatDataset class 작성
- huggingface에서 데이터를 불러오는 경우, new_data 폴더에 있는 txt파일로 데이터를 불러오는 경우, 모두 구현
  - getitem의 output으로 input_ids, attention_mask, label_ids를 반환하도록 함
- TimelyChatDataset class의 getitem도 input_ids, attention_mask, label_ids를 반환하도록 수정

scripts/run_train.py 수정
- train_dataset_path, val_dataste_path에서 "gapchat"이 있을 경우 GapChatDataset으로 불러오도록 코드 수정
- model forward시 input_ids, attention_mask, label_ids를 input으로 받도록 수정
- validation loss 및 ppl 계산시 평균값을 사용하도록 수정

2024-09-02 06:05 UTC, sb-jang commented on resources/gapchat/new_data/time_tag_1_gpt_3.5.jsonl
> +{"speaker_1": [], "speaker_2": []} #1 day, 1 month여야 하는데 공백이 추가됨.그래서 하나씩 다 밀린느낌
여기에 # 있어도 load 할 때 오류 안 뜨나요?

2024-09-02 06:21 UTC, sb-jang commented on resources/gapchat/prompt.py
> +    prompt = ""
```suggestion
```

2024-09-02 06:27 UTC, sb-jang commented on resources/gapchat/prompt.py
> +        raw_text = response["choices"][0]["text"]
```suggestion
    response = openai.ChatCompletion.create(
            model=model_name,
            messages=[messages],
    )
    raw_text = response["choices"][0]["message"]["content"]
```

2024-09-02 06:27 UTC, sb-jang commented on resources/gapchat/prompt.py
> +        raw_text = response["choices"][0]["text"]
text-davinci-003도 쓰나요? 안 쓰면 간단하게 줄여도 될 듯합니다

2024-09-02 06:35 UTC, sb-jang commented on resources/gapchat/prompt.py
> +            extracted_events = [f"speaker_{part.strip()}" for part in parts if part]
이 케이스는 어떤 raw_text를 커버하기 위한 건가요? parts를 이렇게 split 하면 왠지 이상해질 것 같은 느낌?

2024-09-02 06:37 UTC, sb-jang commented on resources/gapchat/prompt.py
> +    data = json.load(file)
```suggestion
    with open(data_path, "r", encoding="utf-8") as file:
        data = json.load(file)
```

2024-09-02 06:46 UTC, sb-jang commented on resources/gapchat/prompt.py
> +def get_chatgpt_response(content: Text, task: Text):
```suggestion
def get_chatgpt_response(content: str, task: str) -> Union[str, List[str]]:
```

2024-09-02 06:47 UTC, sb-jang commented on resources/gapchat/prompt.py
> +from typing import Text
```suggestion
from typing import List, Union
```

2024-09-02 06:52 UTC, sb-jang commented on resources/gapchat/prompt.py
> +def read_conversations(data_path: Text):
```suggestion
def read_conversations(data_path: str) -> List[str]:
```

2024-09-02 06:54 UTC, sb-jang commented on resources/gapchat/prompt.py
> +def read_log_data(data_path: Text):
```suggestion
def read_log_data(data_path: str) -> List[Dict]:
```

2024-09-02 07:03 UTC, sb-jang commented on resources/gapchat/prompt.py
> +def read_events(data_path: Text):
```suggestion
def read_events(data_path: str) -> Union[List[Dict], List[str]]:
```

2024-09-02 07:04 UTC, sb-jang commented on resources/gapchat/prompt.py
> +    data = json.load(file)
```suggestion
    with open(data_path, "r", encoding="utf-8") as file:
        data = json.load(file)
```

2024-09-02 07:22 UTC, sb-jang commented on resources/gapchat/prompt.py
> +            events.append(json.dumps(tmp_events, indent=4))
```suggestion
        event = {
           f"speaker_{id}": item[f"speaker_{id}"] if f"speaker_{id}" in item and item[f"speaker_{id}"] != ["Not mentioned."] else ""
           for id in [1, 2]
        }
        
        # if all empty, append empty string
        if not all(event.values()):
            events.append("")
            continue
        
        events.append(json.dumps(event, indent=4))
```

2024-09-02 07:23 UTC, sb-jang commented on resources/gapchat/prompt.py
> +def extract_events(data_path: Text):
```suggestion
def extract_events(data_path: str) -> None:
```

2024-09-02 07:30 UTC, sb-jang commented on resources/gapchat/prompt.py
> +    json.dump(events_list, events_file, indent=4)
```suggestion
    events_list = []
    conversations = read_conversations(data_path)
    for conversation in conversations:
        print(conversation)
        extracted_events = get_chatgpt_response(conversation, task="events")
        print(extracted_events)
        speaker_1_event = "Not mentioned."
        speaker_2_event = "Not mentioned."
        for event in extracted_events:
            if "speaker_1" in event:
                speaker_1_event = event.split("speaker_1:")[1].strip()
            elif "speaker_2" in event:
                speaker_2_event = event.split("speaker_2:")[1].strip()
        events_list.append({
            "speaker_1" : speaker_1_event.split(", "),
            "speaker_2" : speaker_2_event.split(", "),
        })
        
    with open(f"./new_data/{args.split}/extracted_events.json", 'a+', encoding='utf-8') as events_file:
        json.dump(events_list, events_file, indent=4)
```

2024-09-02 07:34 UTC, sb-jang commented on resources/gapchat/prompt.py
> +    json.dump(events_list, events_file, indent=4)
```suggestion
def get_events_from_logs(log_path: str) -> None:
    events_list = []
    with open(log_path, 'r', encoding='utf-8') as log_file:
        log_data = log_file.readlines()
    counter = 0
    for line in log_data:
        print(counter)
        line_data = json.loads(line.strip())
        response = line_data["choices"][0]["message"]["content"]
        extracted_events = response.split("\n")
        print(extracted_events)
        speaker_1_event = " Not mentioned."
        speaker_2_event = " Not mentioned."
        for event in extracted_events:
            if "speaker_1" in event:
                speaker_1_event = event.split("speaker_1:")[1].strip()
            elif "speaker_2" in event:
                speaker_2_event = event.split("speaker_2:")[1].strip()
        speaker_1_event_lst = [i.strip() for i in speaker_1_event.split(",")]
        speaker_2_event_lst = [i.strip() for i in speaker_2_event.split(",")]
        events_list.append({
            "speaker_1" : speaker_1_event_lst,
            "speaker_2" : speaker_2_event_lst,
        })
        counter += 1
        
    with open(f"./new_data/{args.split}/extracted_events", 'a+', encoding='utf-8') as events_file:
        json.dump(events_list, events_file, indent=4)
```

2024-09-02 08:05 UTC, sb-jang commented on resources/gapchat/prompt.py
> +        time_tagged_file.write(json.dumps(time_tag) + "\n")
```suggestion
def estimate_time(event_path: str) -> None:
    tagged_list = []
    counter = 500
    events = read_events(event_path)
    for event in events[500:]:
        time_tag = {
            "speaker_1": [],
            "speaker_2": []
        }
        if event != "":
            print(f"Processing {counter}")
            extracted_time = get_chatgpt_response(event, task="duration")
            if len(extracted_time) == 2:
                for time in extracted_time:
                    time_split = time.split(":")
                    parts = time_split[1].split(",")
                    speaker = time_split[0].replace(" ", "").lower()
                    for part in parts: # one event in a specific speaker
                        if "->" in part:
                            duration = part.split("->")[1].strip()
                            time_tag[speaker].append(duration)
        tagged_list.append(time_tag)
        counter += 1
        
        with open(f"./new_data/{args.split}/time_tag.jsonl", 'a+', encoding='utf-8') as time_tagged_file:
            for time_tag in tagged_list:
                time_tagged_file.write(json.dumps(time_tag) + "\n")
```

2024-09-02 08:08 UTC, sb-jang commented on resources/gapchat/prompt.py
> +        time_tagged_file.write(json.dumps(time_tag) + "\n")
기존 코드에서 len(extracted_time) == 1일 때 time.split을 하면 이전 스텝에서 len(extracted_time) == 2일 때 할당된 outdated value가 들어가서 (아마도 의도하신) extracted_time[0].split 했을 때랑 값이 달라지게 됩니다. 이 부분이 데이터 만들 때 반영되었을 것 같은데 확인 한번 부탁드립니다.

2024-09-02 08:15 UTC, sb-jang commented on resources/gapchat/prompt.py
> +        event_schedule_file.write(json.dumps(schedule) + "\n")
```suggestion
def get_schedule(event_path: str) -> None:
    events = read_events(event_path)
    counter = 0
    print(len(events))
    schedules = []
    for event in events:
        print(json.dumps(event, indent=4))
        schedule = {
            "speaker_1": [],
            "speaker_2": []
        }
        if event != "":
            print(f"Processing {counter}")
            event_schedule = get_chatgpt_response(event, task="schedule")
            if event_schedule == "Fail":
                print(counter, "fail")
            schedules.append(event_schedule)
        counter += 1
        
        with open(f"./new_data/{args.split}/schedule.jsonl", 'a+', encoding='utf-8') as event_schedule_file:
            for schedule in schedules:
                event_schedule_file.write(json.dumps(schedule) + "\n")
```

2024-09-02 08:19 UTC, sb-jang commented on resources/gapchat/prompt.py
> +        event_schedule_file.write(json.dumps(schedule) + "\n")
다른 함수들과 달리 여기서는 empty schedule을 파일에 쓰지 않고 스킵하는데 schedule만 이렇게 하는 이유가 있나요? 그리고 event_schedule == "Fail"일 때도 파일에 쓰는 것도 의도하신 건지 궁금합니다.

2024-09-02 08:59 UTC, sb-jang commented on resources/gapchat/prompt.py
> +    conversation_file.write(json.dumps(response) + "\n")
```suggestion
def get_evaluation_conversation(save_path: str) -> None:
    prompt = """
    You are having a multi-session conversation with another speaker with the following conditions and example.
    
    # conditions:
    1. You are updating your current daily events.
    2. You are aware of the rough time estimation to finish different events.
    3. The conversation contains 3 sessions. 
    4. There is a time gap between each session.

    # your events:
    {events}

    # time gap:
    {gap}
    """

    gap_prompt = """
    It's been {gap}, and you talk with 
    """

    log_file_path = "./data/new_data/self_chatgpt_log.jsonl"
    with open(log_file_path, "a+", encoding='utf-8') as log_file, open(save_path, 'a+', encoding='utf-8') as conversation_file:
        response = {}
        messages = {
            "role": "user", 
            "content": prompt}
        response = openai.ChatCompletion.create(
                model=model_name,
                messages=[messages]
        )
        log_file.write(json.dumps(response) + "\n")

        raw_text = response["choices"][0]["message"]["content"]
        response = {
            "dialog": raw_text
        }
        conversation_file.write(json.dumps(response) + "\n")
```

2024-09-02 09:05 UTC, sb-jang commented on scripts/run_train.py
>          val_loss /= num_non_mask
```suggestion
    denominator = num_non_mask if model_type == "causal" else len(dataloader)
    val_loss /= denominator
    val_ppl = torch.exp(val_loss)
    
    return val_loss.item(), val_ppl.item()
```

2024-09-02 09:05 UTC, sb-jang commented on scripts/run_train.py
> +    return val_mean_loss.item(), val_ppl.item()
```suggestion
```

2024-09-02 09:06 UTC, sb-jang commented on scripts/run_train.py
> +    return val_mean_loss.item(), val_ppl.item()
causal LM일 때는 num_non_mask로만 나눠주면 돼서 위처럼 denominator로 처리해보았습니다.

2024-09-02 09:14 UTC, sb-jang commented on timely_chat/dataset.py
> +            attention_mask = self.tokenizer(context, padding="max_length", truncation=True)["attention_mask"]
```suggestion
            tokenized_inputs = self.tokenizer(context, padding="max_length", truncation=True)
            input_ids = tokenized_inputs["input_ids"]
            attention_mask = tokenized_inputs["attention_mask"]
            label_ids = self.tokenizer(response, padding="max_length", truncation=True)["input_ids"]
        else:
            context += response
            tokenized_inputs = self.tokenizer(context, padding="max_length", truncation=True)
            input_ids = tokenized_inputs["input_ids"]
            attention_mask = tokenized_inputs["attention_mask"]
```

2024-09-02 09:20 UTC, sb-jang commented on timely_chat/dataset.py
>  from transformers import AutoTokenizer
```suggestion
import os

import torch
from torch.utils.data import Dataset
from transformers import AutoTokenizer
```

2024-09-02 09:23 UTC, sb-jang commented on timely_chat/dataset.py
> +            self.data_type = 'both'
```suggestion
        filename = os.path.basename(self.data_path)
        self.data_type = filename.split(".")[0]
```

2024-09-02 09:28 UTC, sb-jang commented on timely_chat/dataset.py
> +                    text += f"{self.speaker_token} speaker_1: {self.utterance_token} {line.split('\\n')[0].split("text:")[1]} "
```suggestion
                content = line.split('\\n')[0].split("text:")[1]
                if content != "":
                    text += f"{self.speaker_token} speaker_1: {self.utterance_token} {content} "
```

2024-09-02 09:37 UTC, sb-jang commented on timely_chat/dataset.py
> +                            "Schedule":f"{self.speaker_token} speaker_1: {schedule.strip()}",
speaker_token은 대화 컨텍스트에서 speaker, time, utterance를 구분하기 위해 도입한 토큰이라 progress, schedule에서는 speaker_token을 넣어주지 않아도 될 것 같은데 어떻게 생각하세요?

2024-09-02 09:39 UTC, sb-jang commented on timely_chat/dataset.py
> +    def _set_up(self):
```suggestion
    def _set_up(self) -> List[Dict[str, str]]:
```

2024-09-02 09:50 UTC, sb-jang commented on resources/gapchat/prepare_data.py
> +
```suggestion
```

2024-09-02 11:02 UTC, sb-jang commented on resources/gapchat/prepare_data.py
> +                print(index)
```suggestion
            if event_length != time_tag_length:
                raise ValueError(f"Event and time tag mismatch at index {index}.")
```

2024-09-02 11:34 UTC, sb-jang commented on resources/gapchat/prepare_data.py
> +                            print(f"finished: {finished_text}\nto_do: {to_do_text}")
```suggestion
                        if (len(schedule_lst_text)==0) or ("No event" in schedule_lst_text[0]) or ("No schedule" in schedule_lst_text[0]) or ("Not enough information" in schedule_lst_text[0]) or ("Fail" in schedule_lst_text[0]):
                            continue

                        for s in schedule_lst_text: # for each event
                            step_lst = s.split(", ")
                            time_pattern = re.compile(r'\b\d+\s*(?:week|weeks|day|days|hour|hours|month|months|minute|minutes|years|year|semester|semesters)\b', re.IGNORECASE)
                            parentheses_pattern = re.compile(r'\(.*?\)', re.IGNORECASE)
                            step_time_info = []
                            for task in step_lst:
                                task = re.sub(parentheses_pattern, '', task).strip()
                                for match in time_pattern.finditer(task):
                                    step_time_info.append(match.group())
                            for step_idx in range(len(step_time_info)): # for each step
                                cumulated_step_time = sum_time_units(step_time_info[:step_idx+1])
                                progress_label = get_progress_label(gap, cumulated_step_time)
                                if progress_label == "Finished.":
                                    finished_text += step_lst[step_idx]+", "
                                else:
                                    to_do_text += step_lst[step_idx]+", "
                        finished_text = finished_text[:-2]
                        to_do_text = to_do_text[:-2]
                        print(f"finished: {finished_text}\nto_do: {to_do_text}")
```

2024-09-02 12:09 UTC, sb-jang commented on resources/gapchat/prepare_data.py
> +                        i += 1
```suggestion
                    cur_speaker = conversation["sessions"][session_idx][i]["speaker"]
                    if cur_speaker in ["speaker_1", "speaker_2"]:
                        utterance_text, i = merge_utterance(conversation, session_idx, i)
                        if cur_speaker == speaker:
                            human_lst.append(utterance_text)
                        else:
                            machine_lst.append(utterance_text)
                            if len(human_lst) == 0:
                                human_lst.append("")
                    i += 1
```

2024-09-02 12:18 UTC, sb-jang commented on resources/gapchat/prepare_data.py
> +                        )
```suggestion
                    suffix = "\tepisode_done:True" if i == n_turn - 1 else ""
                    parlai_format_file.write(f"text:{utterance_text}\\n Progress: {event_text}\tlabels:{label_text}{suffix}\n")
                    parlai_schedule_format_file.write(f"text:{utterance_text}\\n Schedule: finished:{finished_text} to-do: {to_do_text}\tlabels:{label_text}{suffix}\n")
                    parlai_both_format_file.write(f"text:{utterance_text}\\n Progress: {event_text}\\n Schedule: finished:{finished_text} to-do:{to_do_text}\tlabels:{label_text}{suffix}\n")
```

2024-09-02 12:25 UTC, sb-jang commented on resources/gapchat/prepare_data.py
> +                event_cnt += 1
```suggestion
            if session_idx != 0:
                event_cnt += 2 if session_idx == (session_length - 1) else 1
```

2024-09-02 12:37 UTC, sb-jang commented on resources/gapchat/prepare_data.py
> +
```suggestion

    parlai_format_file.close()
    parlai_schedule_format_file.close()
    parlai_both_format_file.close()
    
```

2024-09-02 12:37 UTC, sb-jang commented on resources/gapchat/prepare_data.py
> +def prepare_time_aware_data(args, conversation_path, events_path, time_tag_path, schedule_path):
```suggestion
def prepare_time_aware_data(args, conversation_path: str, events_path: str, time_tag_path: str, schedule_path: str) -> None:
```

2024-09-02 12:39 UTC, sb-jang commented on resources/gapchat/prepare_data.py
> +def merge_utterance(conversation, session_idx, utterance_idx):
```suggestion
def merge_utterance(conversation: Dict, session_idx: int, utterance_idx: int) -> Tuple[str, int]:
```

2024-09-02 12:55 UTC, sb-jang commented on resources/gapchat/prepare_data.py
> +def convert_minutes(total_minutes):
```suggestion
def convert_minutes(total_minutes: int) -> str:
```

2024-09-02 13:06 UTC, sb-jang commented on resources/gapchat/prepare_data.py
> +def sum_time_units(time_list):
```suggestion
def sum_time_units(time_list: List[str]) -> str:
```

2024-09-02 13:07 UTC, sb-jang commented on resources/gapchat/prepare_data.py
> +def get_progress_label(gaps, duration):
```suggestion
def get_progress_label(gaps: str, duration: str) -> str:
```

2024-09-02 13:14 UTC, sb-jang commented on resources/gapchat/prepare_data.py
> +            return "No significant progress"
```suggestion
    if gaps == "0 s" or "N/A" in duration:
        return "No significant progress."
        
    if "indefinite" in duration:
        duration = "2 years"
    if "ongoing" in duration:
        duration = "1 day"
        
    gap_time = time_to_minutes(gaps)
    duration_time = time_to_minutes(duration)
    if gap_time >= duration_time:
        return "Finished."
    elif gap_time >= 0.75 * duration_time:
        return "Three-forth Finished."
    elif gap_time >= 0.5 * duration_time:
        return "Half Finished."
    elif gap_time >= 0.25 * duration_time:
        return "One-forth Finished."

    return "No significant progress"
```

2024-09-02 13:24 UTC, sb-jang requested changes
중복된 것들도 하나하나 코멘트를 달다보니 코멘트가 많아졌는데요,
공통적으로 리뷰드릴 부분을 요약드리면 다음과 같습니다.

1. 조건문 간략화
- Early return 등으로 중첩 의문문이나 if-else 패턴을 최대한 제거하기
2. 함수 input/output typing하기
- 가급적 docstring도 함께 작성해주시면 좋습니다.
3. file close 제때 하기
- 되도록 with문을 쓰고, 그렇지 않다면 함수 끝에 close 호출하기
4. 가독성을 위한 리팩토링
- List/Dictionary comprehension 사용
- 변수 도입해서 함수 중복 호출이나 중복 코드 제거
5. Bug fix
- 버그 같아 보이는 부분에 code suggestion과 간단한 질문 등을 남겨두었습니다.

2024-09-04 12:25 UTC, minjin-jeon commented on resources/gapchat/prompt.py
> +            extracted_events = [f"speaker_{part.strip()}" for part in parts if part]
raw_text안에 speaker_1과 speaker_2가 둘다 있는데, \n으로 분리가 되어 있지 않을 때 파싱하는 코드입니다.

"speaker_2: hi speaker_1: hello" 이렇게 있을 때, speaker_로 split하면 ['', '2: hi ', '1: hello'] 이렇게 결과가 나와서, list안의 component가 공백이 아닐 경우에 그대로 speaker_와 붙여서 결과를 저장하도록 하는 코드..입니다!

만약에 "speaker_1: talking about with speaker_2" 이런 식의 데이터가 있으면 문제가 되긴 합니다.. 거의 없긴한데..

2024-09-04 12:54 UTC, minjin-jeon commented on resources/gapchat/prompt.py
> +        event_schedule_file.write(json.dumps(schedule) + "\n")
의도하긴 했지만, empty schedule을 파일에 쓰는게 더 나은거 같습니다.!

2024-09-04 14:19 UTC, minjin-jeon commented on timely_chat/dataset.py
> +                            "Schedule":f"{self.speaker_token} speaker_1: {schedule.strip()}",
제가 생각했을 때는 대화 컨텍스트와 일관되게 "speaker_1","speaker_2"가 사전에 정해진 speaker임을 바로 인식할 수 있도록 쓰는게 좋을거 같긴한데.. 없어도 큰 문제는 없을 것 같습니다!

2024-09-05 08:02 UTC, minjin-jeon commented on resources/gapchat/prompt.py
> +        time_tagged_file.write(json.dumps(time_tag) + "\n")
이 부분 수정해서 다시 데이터 구축했습니다.

2024-09-05 08:02 UTC, minjin-jeon commented on resources/gapchat/prompt.py
> +        raw_text = response["choices"][0]["text"]
넵 해당 코드 삭제했습니다

2024-09-19 06:52 UTC, closed without merging